/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankersalgo;

/**
 *
 * @author Juliana
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public Dashboard() {
        initComponents();
    }

    private BankersAlgorithm bankersAlgo = new BankersAlgorithm();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogCheckin = new javax.swing.JDialog();
        jlblTitleCheckin = new javax.swing.JLabel();
        jlblSearchGuest = new javax.swing.JLabel();
        jtxtFieldSearchGuest = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jSpinner6 = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jbtnCloseCheckin = new javax.swing.JButton();
        jbtnSafely = new javax.swing.JButton();
        jbtnConfirmAllocation = new javax.swing.JButton();
        jDialogCheckout = new javax.swing.JDialog();
        jlblTitleCheckout = new javax.swing.JLabel();
        jlblSearch = new javax.swing.JLabel();
        jtxtFieldSearch = new javax.swing.JTextField();
        jlblNote = new javax.swing.JLabel();
        jbtnCheckoutClose = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jbtnSubmit = new javax.swing.JButton();
        jDialogArchived = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnCloseArchived = new javax.swing.JButton();
        jtxtFieldSearchBard = new javax.swing.JTextField();
        jbtnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProcesses = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblResourceAllocation = new javax.swing.JTable();
        jBtnCheckin = new javax.swing.JButton();
        jBtnCheckout = new javax.swing.JButton();
        jBtnArchived = new javax.swing.JButton();
        jlblProcesses = new javax.swing.JLabel();
        jlblResourceAllocation = new javax.swing.JLabel();
        jlblTitleDashboard = new javax.swing.JLabel();

        jlblTitleCheckin.setText("Resource Allocation Check-In");

        jlblSearchGuest.setText("Guest Name (Process ID)");

        jtxtFieldSearchGuest.setText("name");
        jtxtFieldSearchGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFieldSearchGuestActionPerformed(evt);
            }
        });

        jLabel6.setText("Room Allocation");

        jLabel7.setText("Regular Suite");

        jLabel8.setText("Deluxe Suites");

        jLabel9.setText("Staff Need");

        jLabel10.setText("Max Need (Room Type)");

        jLabel11.setText("Max Regular");

        jLabel12.setText("Max Deluxe");

        jLabel13.setText("Max Staff Need");

        jLabel14.setText("Available Resources");

        jLabel15.setText("Regular:");

        jLabel16.setText("Deluxe:");

        jLabel17.setText("Staff: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel15)
                .addGap(79, 79, 79)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(93, 93, 93))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jbtnCloseCheckin.setText("Close");
        jbtnCloseCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseCheckinActionPerformed(evt);
            }
        });

        jbtnSafely.setText("Verify Safety");

        jbtnConfirmAllocation.setText("Confirm Allocation");
        jbtnConfirmAllocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmAllocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogCheckinLayout = new javax.swing.GroupLayout(jDialogCheckin.getContentPane());
        jDialogCheckin.getContentPane().setLayout(jDialogCheckinLayout);
        jDialogCheckinLayout.setHorizontalGroup(
            jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCheckinLayout.createSequentialGroup()
                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogCheckinLayout.createSequentialGroup()
                        .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogCheckinLayout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jlblTitleCheckin))
                            .addGroup(jDialogCheckinLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(jlblSearchGuest)
                                    .addComponent(jtxtFieldSearchGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCheckinLayout.createSequentialGroup()
                                        .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSpinner3)
                                            .addGroup(jDialogCheckinLayout.createSequentialGroup()
                                                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(5, 5, 5))
                                    .addComponent(jLabel10)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCheckinLayout.createSequentialGroup()
                                        .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jDialogCheckinLayout.createSequentialGroup()
                                                .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCheckinLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(178, 178, 178)))
                                        .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jSpinner6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13))))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCheckinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnCloseCheckin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnSafely)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnConfirmAllocation)
                .addGap(25, 25, 25))
            .addGroup(jDialogCheckinLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogCheckinLayout.setVerticalGroup(
            jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCheckinLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlblTitleCheckin)
                .addGap(33, 33, 33)
                .addComponent(jlblSearchGuest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtFieldSearchGuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(9, 9, 9)
                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCloseCheckin)
                    .addComponent(jbtnSafely)
                    .addComponent(jbtnConfirmAllocation))
                .addGap(17, 17, 17))
        );

        jDialogCheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialogCheckout.setEnabled(true);
        jDialogCheckout.setMaximumSize(new java.awt.Dimension(474, 646));
        jDialogCheckout.setMinimumSize(new java.awt.Dimension(474, 646));
        jDialogCheckout.setPreferredSize(new java.awt.Dimension(474, 646));

        jlblTitleCheckout.setText("Guest Check-Out");

        jlblSearch.setText("Search guest");

        jtxtFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFieldSearchActionPerformed(evt);
            }
        });

        jlblNote.setText("Start typing to find your reservation");

        jbtnCheckoutClose.setText("Close");
        jbtnCheckoutClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCheckoutCloseActionPerformed(evt);
            }
        });

        jbtnSubmit.setText("Complete Check-Out");

        javax.swing.GroupLayout jDialogCheckoutLayout = new javax.swing.GroupLayout(jDialogCheckout.getContentPane());
        jDialogCheckout.getContentPane().setLayout(jDialogCheckoutLayout);
        jDialogCheckoutLayout.setHorizontalGroup(
            jDialogCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCheckoutLayout.createSequentialGroup()
                .addGroup(jDialogCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogCheckoutLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jlblNote))
                    .addGroup(jDialogCheckoutLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jDialogCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTitleCheckout)
                            .addComponent(jlblSearch))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jDialogCheckoutLayout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCheckoutLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnCheckoutClose)
                .addGap(35, 35, 35)
                .addComponent(jbtnSubmit)
                .addGap(38, 38, 38))
        );
        jDialogCheckoutLayout.setVerticalGroup(
            jDialogCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCheckoutLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlblTitleCheckout)
                .addGap(29, 29, 29)
                .addComponent(jlblSearch)
                .addGap(18, 18, 18)
                .addComponent(jtxtFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblNote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 396, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jDialogCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCheckoutClose)
                    .addComponent(jbtnSubmit))
                .addGap(30, 30, 30))
        );

        jDialogArchived.setAutoRequestFocus(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jbtnCloseArchived.setText("Close");
        jbtnCloseArchived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseArchivedActionPerformed(evt);
            }
        });

        jtxtFieldSearchBard.setText("jTextField1");

        jbtnSearch.setText("Search");

        jLabel1.setText("Archived Records");

        javax.swing.GroupLayout jDialogArchivedLayout = new javax.swing.GroupLayout(jDialogArchived.getContentPane());
        jDialogArchived.getContentPane().setLayout(jDialogArchivedLayout);
        jDialogArchivedLayout.setHorizontalGroup(
            jDialogArchivedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogArchivedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnCloseArchived)
                .addGap(52, 52, 52))
            .addGroup(jDialogArchivedLayout.createSequentialGroup()
                .addGroup(jDialogArchivedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogArchivedLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jDialogArchivedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDialogArchivedLayout.createSequentialGroup()
                                .addComponent(jtxtFieldSearchBard, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnSearch))))
                    .addGroup(jDialogArchivedLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jLabel1)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jDialogArchivedLayout.setVerticalGroup(
            jDialogArchivedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogArchivedLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jDialogArchivedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFieldSearchBard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearch))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jbtnCloseArchived)
                .addGap(21, 21, 21))
        );

        jScrollPane4.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        jtblProcesses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Guests", "Allocated Regular", "Allocated Deluxe", "Allocated Staff", "Max Regular", "Max Deluxe", "Max Staff"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblProcesses);

        jtblResourceAllocation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Resource Type", "Max Capacity", "Allocated", "Available", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtblResourceAllocation);

        jBtnCheckin.setText("Check in");
        jBtnCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCheckinActionPerformed(evt);
            }
        });

        jBtnCheckout.setText("Check out");
        jBtnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCheckoutActionPerformed(evt);
            }
        });

        jBtnArchived.setText("Archived");
        jBtnArchived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnArchivedActionPerformed(evt);
            }
        });

        jlblProcesses.setText("Processes");

        jlblResourceAllocation.setText("Current Resource Allocation Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jBtnCheckin)
                        .addGap(80, 80, 80)
                        .addComponent(jBtnCheckout)
                        .addGap(79, 79, 79)
                        .addComponent(jBtnArchived))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jlblProcesses))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jlblResourceAllocation)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlblProcesses)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblResourceAllocation)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCheckin)
                    .addComponent(jBtnCheckout)
                    .addComponent(jBtnArchived))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jlblTitleDashboard.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlblTitleDashboard.setText("Hotel Management Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jlblTitleDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jlblTitleDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtFieldSearchGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFieldSearchGuestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFieldSearchGuestActionPerformed

    private void jbtnConfirmAllocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmAllocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnConfirmAllocationActionPerformed

    private void jtxtFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFieldSearchActionPerformed

    private void jbtnCheckoutCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCheckoutCloseActionPerformed
        jDialogCheckout.setVisible(false); // Close the checkout dialog
    }//GEN-LAST:event_jbtnCheckoutCloseActionPerformed

    private void jBtnCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCheckinActionPerformed
        jDialogCheckin.pack();
        jDialogCheckin.setLocationRelativeTo(this);
        jDialogCheckin.setVisible(true);
    }//GEN-LAST:event_jBtnCheckinActionPerformed

    private void jBtnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCheckoutActionPerformed
        jDialogCheckout.pack();
        jDialogCheckout.setLocationRelativeTo(this);
        jDialogCheckout.setVisible(true);
    }//GEN-LAST:event_jBtnCheckoutActionPerformed

    private void jBtnArchivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnArchivedActionPerformed
        jDialogCheckout.pack();
        jDialogCheckout.setLocationRelativeTo(this);
        jDialogCheckout.setVisible(true);
    }//GEN-LAST:event_jBtnArchivedActionPerformed

    private void jbtnCloseCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseCheckinActionPerformed
        jDialogCheckin.setVisible(false); // Close the check-in dialog
    }//GEN-LAST:event_jbtnCloseCheckinActionPerformed

    private void jbtnCloseArchivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseArchivedActionPerformed
        jDialogArchived.setVisible(false);
    }//GEN-LAST:event_jbtnCloseArchivedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnArchived;
    private javax.swing.JButton jBtnCheckin;
    private javax.swing.JButton jBtnCheckout;
    private javax.swing.JDialog jDialogArchived;
    private javax.swing.JDialog jDialogCheckin;
    private javax.swing.JDialog jDialogCheckout;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnCheckoutClose;
    private javax.swing.JButton jbtnCloseArchived;
    private javax.swing.JButton jbtnCloseCheckin;
    private javax.swing.JButton jbtnConfirmAllocation;
    private javax.swing.JButton jbtnSafely;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JButton jbtnSubmit;
    private javax.swing.JLabel jlblNote;
    private javax.swing.JLabel jlblProcesses;
    private javax.swing.JLabel jlblResourceAllocation;
    private javax.swing.JLabel jlblSearch;
    private javax.swing.JLabel jlblSearchGuest;
    private javax.swing.JLabel jlblTitleCheckin;
    private javax.swing.JLabel jlblTitleCheckout;
    private javax.swing.JLabel jlblTitleDashboard;
    private javax.swing.JTable jtblProcesses;
    private javax.swing.JTable jtblResourceAllocation;
    private javax.swing.JTextField jtxtFieldSearch;
    private javax.swing.JTextField jtxtFieldSearchBard;
    private javax.swing.JTextField jtxtFieldSearchGuest;
    // End of variables declaration//GEN-END:variables
}
