/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templat    @Override
    public void adjustmentValueChanged(AdjustmentEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
es/GUIForms/JFrame.java to edit this template
 */
package bankersalgo;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Juliana
 */
public class Dashboard extends javax.swing.JFrame {

    
    public Dashboard() {
        this.setLocationRelativeTo(null);
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        this.setLocation((screenSize.width - frameSize.width) / 2, 
                         (screenSize.height - frameSize.height) / 2);
        //Dashboard - Guest Allocations table
        jScrollPaneDashboard.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPaneDashboard.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jScrollPaneDashboard.setViewportView(jtblGuestAllocations);
        
        //Dashboard - Needs & Request Table
        jScrollPaneDashboard1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPaneDashboard1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jScrollPaneDashboard1.setViewportView(jtblNeedsRequests);
        
        //Rresouc
        jScrollPaneDashboard2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPaneDashboard2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jScrollPaneDashboard2.setViewportView(jtblResourceStatus);
    }
    

    private BankersAlgorithm bankersAlgo = new BankersAlgorithm();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogCheckin = new javax.swing.JDialog();
        jlblTitleCheckin = new javax.swing.JLabel();
        jlblSearchGuest = new javax.swing.JLabel();
        jtxtFieldSearchGuest = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jSpinner6 = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jbtnCloseCheckin = new javax.swing.JButton();
        jbtnSafely = new javax.swing.JButton();
        jbtnConfirmAllocation = new javax.swing.JButton();
        jDialogCheckout = new javax.swing.JDialog();
        jlblTitleCheckout = new javax.swing.JLabel();
        jlblSearch = new javax.swing.JLabel();
        jtxtFieldSearch = new javax.swing.JTextField();
        jlblNote = new javax.swing.JLabel();
        jbtnCheckoutClose = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jbtnSubmit = new javax.swing.JButton();
        jDialogArchived = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnCloseArchived = new javax.swing.JButton();
        jtxtFieldSearchBard = new javax.swing.JTextField();
        jbtnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlblTitleDashboard = new javax.swing.JLabel();
        jlblGuestAllocations = new javax.swing.JLabel();
        jlblNeedRequests = new javax.swing.JLabel();
        jlblResourceStatus = new javax.swing.JLabel();
        jScrollPaneDashboard = new javax.swing.JScrollPane();
        jtblGuestAllocations = new javax.swing.JTable();
        jScrollPaneDashboard1 = new javax.swing.JScrollPane();
        jtblNeedsRequests = new javax.swing.JTable();
        jScrollPaneDashboard2 = new javax.swing.JScrollPane();
        jtblResourceStatus = new javax.swing.JTable();
        jbtnCheckin = new javax.swing.JButton();
        jbtnCheckout = new javax.swing.JButton();
        jbtnArchived = new javax.swing.JButton();

        jlblTitleCheckin.setText("Resource Allocation Check-In");

        jlblSearchGuest.setText("Guest Name (Process ID)");

        jtxtFieldSearchGuest.setText("name");
        jtxtFieldSearchGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFieldSearchGuestActionPerformed(evt);
            }
        });

        jLabel6.setText("Room Allocation");

        jLabel7.setText("Regular Suite");

        jLabel8.setText("Deluxe Suites");

        jLabel9.setText("Staff Need");

        jLabel10.setText("Max Need (Room Type)");

        jLabel11.setText("Max Regular");

        jLabel12.setText("Max Deluxe");

        jLabel13.setText("Max Staff Need");

        jLabel14.setText("Available Resources");

        jLabel15.setText("Regular:");

        jLabel16.setText("Deluxe:");

        jLabel17.setText("Staff: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel15)
                .addGap(79, 79, 79)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(93, 93, 93))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jbtnCloseCheckin.setText("Close");
        jbtnCloseCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseCheckinActionPerformed(evt);
            }
        });

        jbtnSafely.setText("Verify Safety");

        jbtnConfirmAllocation.setText("Confirm Allocation");
        jbtnConfirmAllocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmAllocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogCheckinLayout = new javax.swing.GroupLayout(jDialogCheckin.getContentPane());
        jDialogCheckin.getContentPane().setLayout(jDialogCheckinLayout);
        jDialogCheckinLayout.setHorizontalGroup(
            jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCheckinLayout.createSequentialGroup()
                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogCheckinLayout.createSequentialGroup()
                        .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogCheckinLayout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jlblTitleCheckin))
                            .addGroup(jDialogCheckinLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(jlblSearchGuest)
                                    .addComponent(jtxtFieldSearchGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCheckinLayout.createSequentialGroup()
                                        .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSpinner3)
                                            .addGroup(jDialogCheckinLayout.createSequentialGroup()
                                                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(5, 5, 5))
                                    .addComponent(jLabel10)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCheckinLayout.createSequentialGroup()
                                        .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jDialogCheckinLayout.createSequentialGroup()
                                                .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCheckinLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(178, 178, 178)))
                                        .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jSpinner6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13))))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCheckinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnCloseCheckin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnSafely)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnConfirmAllocation)
                .addGap(25, 25, 25))
            .addGroup(jDialogCheckinLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogCheckinLayout.setVerticalGroup(
            jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCheckinLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlblTitleCheckin)
                .addGap(33, 33, 33)
                .addComponent(jlblSearchGuest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtFieldSearchGuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(9, 9, 9)
                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jDialogCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCloseCheckin)
                    .addComponent(jbtnSafely)
                    .addComponent(jbtnConfirmAllocation))
                .addGap(17, 17, 17))
        );

        jDialogCheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialogCheckout.setMinimumSize(new java.awt.Dimension(474, 646));

        jlblTitleCheckout.setText("Guest Check-Out");

        jlblSearch.setText("Search guest");

        jtxtFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFieldSearchActionPerformed(evt);
            }
        });

        jlblNote.setText("Start typing to find your reservation");

        jbtnCheckoutClose.setText("Close");
        jbtnCheckoutClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCheckoutCloseActionPerformed(evt);
            }
        });

        jbtnSubmit.setText("Complete Check-Out");

        javax.swing.GroupLayout jDialogCheckoutLayout = new javax.swing.GroupLayout(jDialogCheckout.getContentPane());
        jDialogCheckout.getContentPane().setLayout(jDialogCheckoutLayout);
        jDialogCheckoutLayout.setHorizontalGroup(
            jDialogCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCheckoutLayout.createSequentialGroup()
                .addGroup(jDialogCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogCheckoutLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jlblNote))
                    .addGroup(jDialogCheckoutLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jDialogCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTitleCheckout)
                            .addComponent(jlblSearch))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jDialogCheckoutLayout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCheckoutLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnCheckoutClose)
                .addGap(35, 35, 35)
                .addComponent(jbtnSubmit)
                .addGap(38, 38, 38))
        );
        jDialogCheckoutLayout.setVerticalGroup(
            jDialogCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCheckoutLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlblTitleCheckout)
                .addGap(29, 29, 29)
                .addComponent(jlblSearch)
                .addGap(18, 18, 18)
                .addComponent(jtxtFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblNote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 396, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jDialogCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCheckoutClose)
                    .addComponent(jbtnSubmit))
                .addGap(30, 30, 30))
        );

        jDialogArchived.setAutoRequestFocus(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jbtnCloseArchived.setText("Close");
        jbtnCloseArchived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseArchivedActionPerformed(evt);
            }
        });

        jtxtFieldSearchBard.setText("jTextField1");

        jbtnSearch.setText("Search");

        jLabel1.setText("Archived Records");

        javax.swing.GroupLayout jDialogArchivedLayout = new javax.swing.GroupLayout(jDialogArchived.getContentPane());
        jDialogArchived.getContentPane().setLayout(jDialogArchivedLayout);
        jDialogArchivedLayout.setHorizontalGroup(
            jDialogArchivedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogArchivedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnCloseArchived)
                .addGap(52, 52, 52))
            .addGroup(jDialogArchivedLayout.createSequentialGroup()
                .addGroup(jDialogArchivedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogArchivedLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jDialogArchivedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDialogArchivedLayout.createSequentialGroup()
                                .addComponent(jtxtFieldSearchBard, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnSearch))))
                    .addGroup(jDialogArchivedLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jLabel1)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jDialogArchivedLayout.setVerticalGroup(
            jDialogArchivedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogArchivedLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jDialogArchivedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFieldSearchBard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearch))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jbtnCloseArchived)
                .addGap(21, 21, 21))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Olde Hearth || Dashboard");
        setMaximumSize(new java.awt.Dimension(1000, 800));
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setName("FrameDashboard"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 800));

        jlblTitleDashboard.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlblTitleDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitleDashboard.setText("Hotel Management Dashboard");
        jlblTitleDashboard.setToolTipText("");
        jlblTitleDashboard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlblGuestAllocations.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblGuestAllocations.setText("Guest Allocations & Max Claims");

        jlblNeedRequests.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNeedRequests.setText("Needs & Requests");

        jlblResourceStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblResourceStatus.setText("Resource Status");

        jScrollPaneDashboard.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jtblGuestAllocations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Guest ", "Title 2", "Alloc. Regular", "Alloc. Deluxe", "Alloc. Staff", "Max Regular", "Max Deluxe", "Max Staff"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneDashboard.setViewportView(jtblGuestAllocations);

        jtblNeedsRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Guest ", "Need Regular", "Need Deluxe", "Need Staff", "Req. Regular", "Req. Deluxe", "Req. Staff", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneDashboard1.setViewportView(jtblNeedsRequests);

        jtblResourceStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Resource  ", "Max", "Allocated (G1 +G3)", "Available", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneDashboard2.setViewportView(jtblResourceStatus);

        jbtnCheckin.setText("Checkin");
        jbtnCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCheckinActionPerformed(evt);
            }
        });

        jbtnCheckout.setText("Checkout");
        jbtnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCheckoutActionPerformed(evt);
            }
        });

        jbtnArchived.setText("Archived");
        jbtnArchived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnArchivedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneDashboard1)
                    .addComponent(jScrollPaneDashboard2)
                    .addComponent(jlblResourceStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblNeedRequests, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnCheckin)
                        .addGap(31, 31, 31)
                        .addComponent(jbtnCheckout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnArchived))
                    .addComponent(jScrollPaneDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblGuestAllocations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110))
            .addComponent(jlblTitleDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblTitleDashboard)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnCheckin)
                        .addComponent(jbtnCheckout))
                    .addComponent(jbtnArchived))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblGuestAllocations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblNeedRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblResourceStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneDashboard2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtFieldSearchGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFieldSearchGuestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFieldSearchGuestActionPerformed

    private void jbtnConfirmAllocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmAllocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnConfirmAllocationActionPerformed

    private void jtxtFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFieldSearchActionPerformed

    private void jbtnCheckoutCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCheckoutCloseActionPerformed
        jDialogCheckout.setVisible(false); // Close the checkout dialog
    }//GEN-LAST:event_jbtnCheckoutCloseActionPerformed

    private void jbtnCloseCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseCheckinActionPerformed
        jDialogCheckin.setVisible(false); // Close the check-in dialog
    }//GEN-LAST:event_jbtnCloseCheckinActionPerformed

    private void jbtnCloseArchivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseArchivedActionPerformed
        jDialogArchived.setVisible(false);
    }//GEN-LAST:event_jbtnCloseArchivedActionPerformed

    private void jbtnCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCheckinActionPerformed
        jDialogCheckin.pack();
        jDialogCheckin.setLocationRelativeTo(this);
        jDialogCheckin.setVisible(true);
    }//GEN-LAST:event_jbtnCheckinActionPerformed

    private void jbtnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCheckoutActionPerformed
        jDialogCheckout.pack();
        jDialogCheckout.setLocationRelativeTo(this);
        jDialogCheckout.setVisible(true);
    }//GEN-LAST:event_jbtnCheckoutActionPerformed

    private void jbtnArchivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnArchivedActionPerformed
        jDialogArchived.pack();
        jDialogArchived.setLocationRelativeTo(this);
        jDialogArchived.setVisible(true);
    }//GEN-LAST:event_jbtnArchivedActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialogArchived;
    private javax.swing.JDialog jDialogCheckin;
    private javax.swing.JDialog jDialogCheckout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneDashboard;
    private javax.swing.JScrollPane jScrollPaneDashboard1;
    private javax.swing.JScrollPane jScrollPaneDashboard2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnArchived;
    private javax.swing.JButton jbtnCheckin;
    private javax.swing.JButton jbtnCheckout;
    private javax.swing.JButton jbtnCheckoutClose;
    private javax.swing.JButton jbtnCloseArchived;
    private javax.swing.JButton jbtnCloseCheckin;
    private javax.swing.JButton jbtnConfirmAllocation;
    private javax.swing.JButton jbtnSafely;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JButton jbtnSubmit;
    private javax.swing.JLabel jlblGuestAllocations;
    private javax.swing.JLabel jlblNeedRequests;
    private javax.swing.JLabel jlblNote;
    private javax.swing.JLabel jlblResourceStatus;
    private javax.swing.JLabel jlblSearch;
    private javax.swing.JLabel jlblSearchGuest;
    private javax.swing.JLabel jlblTitleCheckin;
    private javax.swing.JLabel jlblTitleCheckout;
    private javax.swing.JLabel jlblTitleDashboard;
    private javax.swing.JTable jtblGuestAllocations;
    private javax.swing.JTable jtblNeedsRequests;
    private javax.swing.JTable jtblResourceStatus;
    private javax.swing.JTextField jtxtFieldSearch;
    private javax.swing.JTextField jtxtFieldSearchBard;
    private javax.swing.JTextField jtxtFieldSearchGuest;
    // End of variables declaration//GEN-END:variables
}
